In [3]:
import pandas as pd
import numpy as np

In [27]:
l=pd.read_csv("labels.csv",header=None)
df=pd.read_csv("data.csv",header=None)
li=l[0]
#df["class"]=li
df

,0,1,2,3,4,5,6,7,8,9,...,390,391,392,393,394,395,396,397,398,399
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.0,253.0,253.0,216.0,93.0,8.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,57.0,123.0,246.0,253.0,170.0,37.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,154.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.0,245.0,79.0,179.0,179.0,73.0,94.0,2.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,106.0,154.0,254.0,...,253.0,253.0,253.0,253.0,208.0,25.0,0.0,0.0,0.0,0.0
996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,184.0,99.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.0,254.0,253.0,248.0,118.0,10.0,0.0,0.0,0.0,0.0
999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,236.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [77]:
#center data and take covariance
ave=np.mean(df,axis=0)
centre=df-ave
cov=np.cov(centre.T)
eigenvalues,eigenvectors=np.linalg.eig(cov)
    
#sort eigenvector acoordinc to eigen values
sorted_i=np.argsort(eigenvalues)[::-1]
sorted_eigenvectors=eigenvectors[:,sorted_i]
    
#project the data on 100 dimensions only
r_eigenvectors=sorted_eigenvectors[:,:100]
r_data=np.dot(centered_data, r_eigenvectors)

In [81]:
data=pd.DataFrame(r_data) 
data

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,476.111547,-691.871574,-705.969989,466.499076,-190.716814,153.891876,145.162461,-140.727950,-200.382430,101.136213,...,87.180150,-89.785449,10.683522,-48.264503,95.656448,5.614497,-80.052147,-0.874854,128.546676,32.685590
1,-164.660031,272.109266,-375.985338,133.300371,370.394464,424.582668,445.838332,-374.654418,-21.425687,-18.160047,...,-43.523211,-1.552294,-36.843195,1.024168,12.858682,-17.776209,-12.747922,107.546875,5.246473,29.628975
2,210.799027,-148.856356,738.628518,-1066.387239,-84.399527,-504.108357,507.928669,179.254465,-402.678676,46.929237,...,-31.281824,-102.902389,18.941192,11.964213,-23.319194,-118.104374,89.864308,-5.267851,-32.216699,-129.461157
3,1511.282664,-203.023483,-595.009414,254.991335,97.497981,-1136.497587,-721.303845,-311.805857,725.216684,-235.336707,...,58.133163,52.125471,37.105361,-4.597336,-31.142359,27.018821,55.284027,-88.148744,43.791186,82.697644
4,1242.806360,256.920727,867.272953,744.118961,425.014585,-314.299176,159.435985,-16.168892,-97.153894,-191.201218,...,-45.863836,58.431891,27.723486,55.802502,-37.561668,-44.721902,-9.195519,-33.291915,26.652172,5.161681
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,503.829132,-1129.428341,-427.297777,254.340445,-200.179725,115.589915,457.855504,540.973761,-96.457850,-109.314852,...,5.895410,10.700580,-40.328936,-5.039325,-31.941954,-72.815034,-27.352817,-57.800443,23.838394,33.918203
996,254.002582,114.927160,926.715142,-372.155285,498.212714,-227.597310,16.090050,199.129408,475.578780,-362.206841,...,33.008011,-69.216081,104.259597,2.278779,-11.248575,52.443927,-64.673602,41.493953,-137.657931,44.128534
997,931.897807,-93.067172,151.364306,854.541957,581.714300,-102.654826,355.024964,-438.990378,-180.270346,-286.823347,...,57.984726,-14.296210,-95.941700,22.795436,1.683645,-110.617895,-13.707272,-36.470958,-30.407308,-36.490802
998,499.804285,-434.035973,-348.027859,794.113319,-328.458701,415.629240,568.087755,-426.150659,46.763446,3.446160,...,12.530912,-114.113917,72.118434,-102.434104,-3.571159,-22.306969,-11.949629,63.429366,-41.888755,-50.044551
999,90.330928,775.390640,-429.473022,482.536673,157.441519,-334.976346,-96.344228,-182.176264,-475.786024,262.495118,...,43.665505,-94.117102,-20.368466,106.833774,-15.539786,-22.620694,109.176059,26.085082,11.622086,-26.167465

In [91]:

class mlp(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1=torch.nn.Linear(100,200)
        self.layer2=torch.nn.Linear(200,200)
        self.layer3=torch.nn.Linear(200,176)
        self.layer4=torch.nn.Linear(176, 10)
    def forward(self, x):
        x=torch.nn.ReLU()(self.layer1(x))
        x=torch.nn.ReLU()(self.layer2(x))
        x=torch.nn.ReLU()(self.layer3(x))
        x=self.layer4(x)
        return x

In [92]:
accuracy

0.1